# Generated by Django 5.2.10 on 2026-01-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_employee_user'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_comment', to='organization.employee')),
                ('task', models.ManyToManyField(to='projects.task')),
            ],
        ),
    ]
