# Generated by Django 5.2.10 on 2026-01-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='comments', to='projects.task'),
        ),
    ]
