# Generated by Django 5.2.10 on 2026-01-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_comment_task_comment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='projects.task'),
        ),
    ]
