# Generated by Django 5.2.9 on 2025-12-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsession',
            name='device_fingerprint_hash',
        ),
        migrations.RemoveField(
            model_name='loginsession',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='loginsession',
            name='revoked',
        ),
    ]
