# Generated by Django 5.2.9 on 2025-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_loginsession_device_fingerprint_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
