# Generated by Django 5.2.9 on 2025-12-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_loginsession_revoked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsession',
            name='revoked',
        ),
    ]
