# Generated by Django 5.2.10 on 2026-01-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_employee_employee_id_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='level',
            field=models.CharField(blank=True, verbose_name='Level'),
        ),
    ]
