# Generated by Django 5.2.10 on 2026-01-27 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_historicallevel_changed_by_level_changed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallevel',
            old_name='changed_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='level',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='level',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
