# Generated by Django 5.2.10 on 2026-01-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_rename_changed_by_historicallevel_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='responsibilities',
        ),
    ]
